# Definindo o nome do Workflow
name: Meu primeiro Workflow no Github Actions

# Definindo quando o Workflow será disparado
on:
  push:
    branches: [ main, develop ]

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: ubuntu-latest
    steps:

    - name: Step 1 - Run a one-line script
      uses: actions/checkout@v4
      run: echo Olá, turma da disciplina GitHub actions!

    - name: Step 2 - Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.

    - name: Step 3
      uses: actions/checkout@v2
      run: echo "Hello World"