# Definindo o nome do Workflow
name: Meu primeiro Workflow no Github Actions

# Definindo quando o Workflow será disparado
on:
  push:
    branches: [ main, develop ]

# Definindo os jobs que o workflow executará
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: self-hosted
    steps:

    - name: Step 1 - Check out the code
      uses: actions/checkout@v4

    - name: Step 2 - Run a one-line script
      run: echo Olá, turma da disciplina GitHub actions! 

    - name: Step 3 - Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.